/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c ifadapter -a ifadapter.h:ifadapter.cpp com.dbus.m-plan.interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "ifadapter.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ifadapter
 */

ifadapter::ifadapter(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ifadapter::~ifadapter()
{
    // destructor
}

QString ifadapter::SendMessage(const QString &cmd)
{
    // handle method call local.qdbuscpp2xml.interfacedescription.SendMessage
    QString out0;
    QMetaObject::invokeMethod(parent(), "SendMessage", Q_RETURN_ARG(QString, out0), Q_ARG(QString, cmd));
    return out0;
}

QString ifadapter::read()
{
    // handle method call local.qdbuscpp2xml.interfacedescription.read
    QString out0;
    QMetaObject::invokeMethod(parent(), "read", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString ifadapter::write()
{
    // handle method call local.qdbuscpp2xml.interfacedescription.write
    QString out0;
    QMetaObject::invokeMethod(parent(), "write", Q_RETURN_ARG(QString, out0));
    return out0;
}

