/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c ifadapter -a ifadapter.h:ifadapter.cpp com.dbus.m-plan.interface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef IFADAPTER_H_1489844758
#define IFADAPTER_H_1489844758

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface local.qdbuscpp2xml.interfacedescription
 */
class ifadapter: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "local.qdbuscpp2xml.interfacedescription")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"local.qdbuscpp2xml.interfacedescription\">\n"
"    <signal name=\"somethingHappened\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"signalMessage\"/>\n"
"    </signal>\n"
"    <method name=\"read\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"write\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"SendMessage\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"cmd\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ifadapter(QObject *parent);
    virtual ~ifadapter();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString SendMessage(const QString &cmd);
    QString read();
    QString write();
Q_SIGNALS: // SIGNALS
    void somethingHappened(const QString &signalMessage);
};

#endif
